#!/usr/bin/env python3
from pathlib import Path
import sys

if len(sys.argv) != 2:
    raise SystemExit('usage: patch_26515_derived_builder.py <derived-26514-builder>')
p = Path(sys.argv[1])
s = p.read_text()

def one(old: str, new: str, label: str) -> None:
    global s
    n = s.count(old)
    if n != 1:
        raise SystemExit(f'{label}: expected exactly one anchor, found {n}')
    s = s.replace(old, new, 1)

# The existing 26514 outer constructor has already proved and reconstructed the exact 26514 base.
one('OUT="$ROOT/build_26514_iris_profiles_controls_outputs"',
    'OUT="$ROOT/build_26515_short_bento_exposure_domain_outputs"', 'inner OUT')
one('WORK="$ROOT/.build_26514_iris_profiles_controls_work"',
    'WORK="$ROOT/.build_26515_short_bento_exposure_domain_work"', 'inner WORK')
one('AFTER="$WORK/candidate26514"', 'AFTER="$WORK/candidate26515"', 'inner candidate')
one('VERSION_NAME="0.9726514"', 'VERSION_NAME="0.9726515"', 'inner version name')
one('VERSION_BUILD="26514"', 'VERSION_BUILD="26515"', 'inner version build')
one('FINAL="$ROOT/IrisCamera-${VERSION_NAME}-${VERSION_BUILD}-iris-profiles-controls-debug.apk"',
    'FINAL="$ROOT/IrisCamera-${VERSION_NAME}-${VERSION_BUILD}-short-bento-domain-fix-debug.apk"',
    'inner final APK')
one('exec > >(tee "$OUT/26514_build.log") 2>&1',
    'exec > >(tee "$OUT/26515_build.log") 2>&1', 'inner build log')

# Add the 26515 deterministic transform as an explicit constructor input.
anchor = 'VALIDATE_26514="'
idx = s.find(anchor)
if idx < 0:
    raise SystemExit('inner VALIDATE_26514 variable missing')
line_end = s.find('\n', idx)
if line_end < 0:
    raise SystemExit('inner VALIDATE_26514 line malformed')
s = s[:line_end+1] + \
    'APPLY_26515="$ROOT/apply_26515_short_bento_exposure_domain.py"\n' + \
    'VALIDATE_26515="$ROOT/validate_26515_short_bento_exposure_domain.py"\n' + s[line_end+1:]

# Require the new helpers wherever the generated constructor checks explicit files.
file_gate = ' "$APPLY_26514" "$VALIDATE_26514"; do'
if s.count(file_gate) != 1:
    raise SystemExit(f'inner helper file gate: expected one anchor, found {s.count(file_gate)}')
s = s.replace(file_gate,
              ' "$APPLY_26514" "$VALIDATE_26514" "$APPLY_26515" "$VALIDATE_26515"; do', 1)

# Apply 26515 only after the proven 26514 candidate exists. apply_26515 writes its rollback patch
# before changing any runtime file.
gate46 = 'pass "GATE 4.6 rollback patch existed before 26514 writes; exact golden-26513 delta validated"'
gate47 = gate46 + r'''

echo "=== GATE 4.7: apply only 26515 Short/Bento exposure-domain ownership fix ==="
BASE26514="$WORK/golden26514"
rm -rf "$BASE26514"; mkdir -p "$BASE26514"
cp -a "$AFTER/." "$BASE26514/"
PATCH26515="$OUT/26515_RUNTIME_DELTA_FROM_GOLDEN_26514.patch"
PATCH26515_SHA="$OUT/26515_RUNTIME_DELTA_FROM_GOLDEN_26514.patch.sha256"
python3 "$APPLY_26515" "$AFTER" --patch-out "$PATCH26515" --patch-sha-out "$PATCH26515_SHA"
( cd "$OUT" && sha256sum -c "$(basename "$PATCH26515_SHA")" )
python3 "$VALIDATE_26515" --base "$BASE26514" --candidate "$AFTER" --apply-script "$APPLY_26515"
pass "GATE 4.7 Short retained; BaselineExposure source/display authority split validated"
'''
one(gate46, gate47, 'insert Gate 4.7')

# Rename proof artifacts generated by the single 26515 Gradle build.
for old, new in (
    ('26514_pre_gradle_audited_runtime.sha256', '26515_pre_gradle_audited_runtime.sha256'),
    ('26514_post_gradle_audited_runtime.sha256', '26515_post_gradle_audited_runtime.sha256'),
    ('26514_gradle_runtime_source_diff.txt', '26515_gradle_runtime_source_diff.txt'),
    ('Gradle preserved audited 26514 runtime source', 'Gradle preserved audited 26515 runtime source'),
    ('26514_arm64_mgc_symbols.txt', '26515_arm64_mgc_symbols.txt'),
    ('26514_armv7_stub_symbols.txt', '26515_armv7_stub_symbols.txt'),
    ('26514_APK.sha256', '26515_APK.sha256'),
    ('26514_candidate_app_source.tar.gz', '26515_candidate_app_source.tar.gz'),
    ('26514_candidate_source.sha256', '26515_candidate_source.sha256'),
    ('GATE 6 exactly one 26514 APK built from exact tested 26513 + Iris controls',
     'GATE 6 exactly one 26515 APK built from exact reconstructed 26514 + Short/Bento domain fix'),
    ('26514 complete: exact tested 26513 image architecture + strict Iris noise profiles/denoise/presentation controls',
     '26515 complete: exact 26514 controls + corrected accepted-Short BaselineExposure ownership'),
):
    s = s.replace(old, new)

# Keep the inherited 26514 DEX proof, then demand the new runtime marker as well.
anchor_sha = 'sha256sum "$FINAL" > "$OUT/26515_APK.sha256"'
if s.count(anchor_sha) != 1:
    raise SystemExit(f'26515 APK SHA anchor count={s.count(anchor_sha)}')
proof = r'''python3 - "$FINAL" <<'PYAPK26515'
import sys, zipfile
with zipfile.ZipFile(sys.argv[1]) as z:
    dex = b''.join(z.read(n) for n in sorted(z.namelist()) if n.endswith('.dex'))
    for marker in (
        b'IRIS_26512_MGC1271_PARITY_VALID',
        b'IRIS_26513_JPEG_COMPLETION_AFTER_SAVE',
        b'IRIS_26514_NOISE_AUTHORITY',
        b'IRIS_26514_DENOISE',
        b'IRIS_26515_SHORT_BASELINE_DOMAIN',
        b'IRIS_26515_FUSED_LINEAR_SOURCE_RESTORE',
        b'IRIS_26515_RENDER_EXPOSURE_AUTHORITY_SPLIT',
    ):
        assert marker in dex, ('missing 26515 DEX marker', marker)
    for bad in (b'IRIS_26509_', b'IRIS_26510_', b'IRIS_26511_'):
        assert bad not in dex, bad
print('PASS: APK proves 26512/26513/26514 lineage plus 26515 Short/Bento domain fix')
PYAPK26515
''' + anchor_sha
one(anchor_sha, proof, '26515 APK proof')

p.write_text(s)
print('PASS: derived 26514 constructor patched to one-build 26515 constructor')
