#!/usr/bin/env python3
from pathlib import Path
import hashlib,sys
if len(sys.argv)!=3: raise SystemExit('usage: validate_26637_r1.py BASE CANDIDATE')
base=Path(sys.argv[1]); cand=Path(sys.argv[2]);
cpp='app/src/main/cpp/iris_heic_jni.cpp'; java='app/src/main/java/com/particlesdevs/photoncamera/processing/ultrahdr/IrisHardwareHevcEncoder.java'; ver='app/version.properties'
b=(base/cpp).read_text(); c=(cand/cpp).read_text(); jb=(base/java).read_text(); jc=(cand/java).read_text(); vb=(base/ver).read_text(); vc=(cand/ver).read_text()
# Reconstruct the only permitted native semantic edits from exact 26636 bytes.
exp=b
exp=exp.replace('#include "plugin_registry.h"\n','#include "plugin_registry.h"\n#include "codecs/hevc_boxes.h"\n',1)
old='''    heif_error err = heif_image_create(info.width, info.height, heif_colorspace_RGB,\n                                       heif_chroma_interleaved_RGBA, &image);\n    if (err.code == heif_error_Ok)\n        err = heif_image_add_plane(image, heif_channel_interleaved, info.width, info.height, 8);\n    if (err.code == heif_error_Ok) {\n        int stride = 0;\n        uint8_t* dst = heif_image_get_plane(image, heif_channel_interleaved, &stride);\n        if (!dst || stride < static_cast<int>(info.width * 4u)) err = heif_error_unsupported_parameter;\n        else for (uint32_t y = 0; y < info.height; ++y)\n            std::memcpy(dst + static_cast<size_t>(y) * stride,\n                        static_cast<uint8_t*>(pixels) + static_cast<size_t>(y) * info.stride,\n                        static_cast<size_t>(info.width) * 4u);\n    }\n'''
new='''    // IRIS_26637_OPAQUE_RGB_HEIC_BASE_OWNER\n    // Android Bitmap remains RGBA_8888 at the JNI boundary, but HEIC camera stills are opaque.\n    // Publish only RGB so libheif cannot synthesize an auxiliary alpha image/item.\n    heif_error err = heif_image_create(info.width, info.height, heif_colorspace_RGB,\n                                       heif_chroma_interleaved_RGB, &image);\n    if (err.code == heif_error_Ok)\n        err = heif_image_add_plane(image, heif_channel_interleaved, info.width, info.height, 8);\n    if (err.code == heif_error_Ok) {\n        int stride = 0;\n        uint8_t* dst = heif_image_get_plane(image, heif_channel_interleaved, &stride);\n        if (!dst || stride < static_cast<int>(info.width * 3u)) err = heif_error_unsupported_parameter;\n        else {\n            const auto* src = static_cast<const uint8_t*>(pixels);\n            for (uint32_t y = 0; y < info.height; ++y) {\n                uint8_t* outRow = dst + static_cast<size_t>(y) * stride;\n                const uint8_t* inRow = src + static_cast<size_t>(y) * info.stride;\n                for (uint32_t x = 0; x < info.width; ++x) {\n                    outRow[x * 3u + 0u] = inRow[x * 4u + 0u];\n                    outRow[x * 3u + 1u] = inRow[x * 4u + 1u];\n                    outRow[x * 3u + 2u] = inRow[x * 4u + 2u];\n                }\n            }\n        }\n    }\n'''
assert exp.count(old)==1; exp=exp.replace(old,new,1)
old2='heif_nclx_color_profile_set_transfer_characteristics(baseNclx, heif_transfer_characteristic_ITU_R_BT_709_5)'
new2='heif_nclx_color_profile_set_transfer_characteristics(baseNclx, heif_transfer_characteristic_IEC_61966_2_1)'
assert exp.count(old2)==1; exp=exp.replace(old2,new2,1)
old3='''    if (!iris26636CallHardwareEncoder(width, height, i420, state->quality, gainMap, state->nals)) {\n        return {heif_error_Encoder_plugin_error, heif_suberror_Unspecified,\n                "Android hardware MediaCodec HEVC encoding failed"};\n    }\n    return heif_error_ok;\n'''
new3='''    if (!iris26636CallHardwareEncoder(width, height, i420, state->quality, gainMap, state->nals)) {\n        return {heif_error_Encoder_plugin_error, heif_suberror_Unspecified,\n                "Android hardware MediaCodec HEVC encoding failed"};\n    }\n    // IRIS_26637_HEVC_ACTUAL_OUTPUT_PROOF\n    // Parse the emitted SPS with the same pinned libheif parser that builds hvcC. Diagnostic only:\n    // never changes encoder selection, input format, quality, or the returned NAL stream.\n    for (const auto& nal : state->nals) {\n        if (nal.size() < 3u || (((nal[0] >> 1) & 0x3f) != 33)) continue;\n        Box_hvcC::configuration cfg{};\n        int codedWidth = 0, codedHeight = 0;\n        const Error parseErr = parse_sps_for_hvcC_configuration(\n                nal.data(), nal.size(), &cfg, &codedWidth, &codedHeight);\n        if (!parseErr) {\n            IRIS26636_LOGI(\n                    "IRIS_26637_HEVC_OUTPUT gainMap=%s chromaFormat=%u bitDepthLuma=%u "\n                    "bitDepthChroma=%u profile=%u level=%u coded=%dx%d",\n                    gainMap ? "true" : "false", static_cast<unsigned>(cfg.chroma_format),\n                    static_cast<unsigned>(cfg.bit_depth_luma),\n                    static_cast<unsigned>(cfg.bit_depth_chroma),\n                    static_cast<unsigned>(cfg.general_profile_idc),\n                    static_cast<unsigned>(cfg.general_level_idc), codedWidth, codedHeight);\n        } else {\n            IRIS26636_LOGE("IRIS_26637_HEVC_OUTPUT SPS parse failed");\n        }\n        break;\n    }\n    return heif_error_ok;\n'''
assert exp.count(old3)==1; exp=exp.replace(old3,new3,1)
old4='if (ok) IRIS26636_LOGI("IRIS_26636_HEIC_ISO21496 hardwareHevc=true baseP3=true gainmapReused=true bytes=%zu", memory.bytes.size());'
new4='if (ok) IRIS26636_LOGI("IRIS_26637_HEIC_ISO21496 hardwareHevc=true opaqueRgb=true baseP3Srgb=true gainmapReused=true bytes=%zu", memory.bytes.size());'
assert exp.count(old4)==1; exp=exp.replace(old4,new4,1)
if exp!=c: raise SystemExit('FAIL native file contains changes beyond exact 26637 semantic transform')
# Java may change only by diagnostic capability log insertion.
jexp=jb
anchor='''        MediaCodecInfo info = choice.info;\n        MediaCodecInfo.CodecCapabilities caps = info.getCapabilitiesForType(choice.mime);\n        MediaCodec codec = null;\n'''
insert='''        MediaCodecInfo info = choice.info;\n        MediaCodecInfo.CodecCapabilities caps = info.getCapabilitiesForType(choice.mime);\n        // IRIS_26637_HEVC_CAPABILITY_PROOF: diagnostic only; encoding contract is unchanged.\n        StringBuilder profileLevels = new StringBuilder();\n        for (MediaCodecInfo.CodecProfileLevel pl : caps.profileLevels) {\n            if (profileLevels.length() > 0) profileLevels.append(',');\n            profileLevels.append(pl.profile).append('/').append(pl.level);\n        }\n        Log.i(TAG, "IRIS_26637_HEVC_CAPS codec=" + info.getName()\n                + " colorFormats=" + Arrays.toString(caps.colorFormats)\n                + " profileLevels=" + profileLevels);\n        MediaCodec codec = null;\n'''
assert jexp.count(anchor)==1; jexp=jexp.replace(anchor,insert,1)
if jexp!=jc: raise SystemExit('FAIL hardware encoder file contains behavior changes beyond capability logging')
vexp=vb.replace('VERSION_NAME=0.9726636','VERSION_NAME=0.9726637').replace('VERSION_BUILD=26636','VERSION_BUILD=26637')
if vexp!=vc: raise SystemExit('FAIL version properties change beyond exact 26637 bump')
print('PASS 26637 semantic validation: opaque RGB + P3/sRGB NCLX + diagnostic-only HEVC proof; no other runtime semantics changed')
